"use client";

import { useCallback, useEffect, useRef, useState, type PointerEvent } from "react";
import { LingbotWorld2Model } from "@reactor-models/lingbot-world-2/core";
import { downloadClipAsFile } from "@reactor-team/js-sdk";
import { IDLE_AXES, axesFromInput, diffAxes, isTypingTarget, type Axes, type AxisCommand } from "../world/lib/controls";
import type { WorldRoom } from "../lib/robot-worlds";
import { composeGymPrompt, phaseLabel, taskPhases, type TaskPhase } from "./reactor-prompts";
import { acceptSequenceChunk, doorSequence, taskSequence, type GenerationSequence } from "./reactor-director";
import { connectionFailure, MAX_CONNECTION_RETRIES, readCooldown, REACTOR_COOLDOWN_KEY, saveCooldown, waitForRetry } from "./reactor-connection";
import styles from "./reactor-gym.module.css";

export interface GeneratedGym { theme: string; image: string; video: string; model: string; seedSource: string }
const errorText = (error: unknown) => error instanceof Error ? error.message : String(error);

export default function ReactorGym({ room, generated, configured, onPhysics, onDoor, nextRoom }: {
  room: WorldRoom; generated?: GeneratedGym; configured: boolean; onPhysics: () => void; onDoor: (path: string) => void; nextRoom?: WorldRoom;
}) {
  const client = useRef<LingbotWorld2Model | null>(null);
  const video = useRef<HTMLVideoElement | null>(null);
  const mounted = useRef(false);
  const keys = useRef(new Set<string>());
  const axes = useRef<Axes>(IDLE_AXES);
  const sent = useRef<Axes>(IDLE_AXES);
  const drag = useRef<{ x: number; y: number; timer?: ReturnType<typeof setTimeout> } | null>(null);
  const generation = useRef(0);
  const seedQueue = useRef<Promise<void>>(Promise.resolve());
  const tokenRef = useRef<string | null>(null);
  const connection = useRef<AbortController | null>(null);
  const closing = useRef<Promise<void>>(Promise.resolve());
  const cooldownUntil = useRef(0);
  const requestedPrompt = useRef("");
  const lastInput = useRef(Date.now());
  const ready = useRef(false);
  const phaseRef = useRef<TaskPhase>("ready");
  const variationRef = useRef(0);
  const customTaskRef = useRef("");
  const directionRef = useRef("");
  const sequence = useRef<GenerationSequence | null>(null);
  const sequenceUpdated = useRef(0);
  const roomRef = useRef(room); roomRef.current = room;
  const image = generated?.image ?? room.image;
  const imageRef = useRef(image); imageRef.current = image;
  const [status, setStatus] = useState("disconnected");
  const [message, setMessage] = useState("Walk through a world generated by Reactor");
  const [error, setError] = useState<string | null>(null);
  const [frames, setFrames] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [phase, setPhase] = useState<TaskPhase>("ready");
  const [variation, setVariation] = useState(0);
  const [paused, setPaused] = useState(false);
  const [busy, setBusy] = useState(false);
  const [captureBusy, setCaptureBusy] = useState(false);
  const [renderedPhase, setRenderedPhase] = useState<TaskPhase | "pending">("pending");
  const [renderedAction, setRenderedAction] = useState("still");
  const [cooldownSeconds, setCooldownSeconds] = useState(0);
  const [retryPending, setRetryPending] = useState(false);
  const [retryMessage, setRetryMessage] = useState("");
  const [taskDraft, setTaskDraft] = useState("");
  const [customTask, setCustomTask] = useState("");
  const [directionDraft, setDirectionDraft] = useState("");
  const [direction, setDirection] = useState("");
  const [directorOpen, setDirectorOpen] = useState(false);
  const [sequenceState, setSequenceState] = useState<GenerationSequence | null>(null);
  const [demoFinished, setDemoFinished] = useState(false);
  const active = status !== "disconnected" && status !== "cooldown";
  // A reset can briefly deliver a black decoder frame; wait for four real model chunks.
  const live = playing && frames >= 96;
  const pausedRef = useRef(false);

  const report = useCallback((cause: unknown) => { if (mounted.current) setError(errorText(cause)); }, []);
  const releaseModel = useCallback((model: LingbotWorld2Model) => {
    const release = async () => {
      try { await model.disconnect(); }
      catch { /* A failed connection may already have been released by Reactor. */ }
      finally { model[Symbol.dispose](); }
    };
    closing.current = closing.current.then(release, release);
    return closing.current;
  }, []);
  const disconnect = useCallback(async (notice = "Reactor session released") => {
    const pendingConnection = connection.current !== null;
    connection.current?.abort(); connection.current = null;
    const model = client.current; client.current = null;
    generation.current++; ready.current = false;
    sequence.current = null;
    keys.current.clear(); axes.current = IDLE_AXES; sent.current = IDLE_AXES;
    pausedRef.current = false;
    if (video.current) { video.current.pause(); video.current.srcObject = null; }
    if (mounted.current) {
      setPlaying(false); setFrames(0); setPaused(false); setBusy(false); setRetryPending(false); setStatus("disconnected"); setMessage(notice);
      setSequenceState(null); setDemoFinished(false);
      setRetryMessage(pendingConnection && cooldownUntil.current > Date.now() ? "Automatic retry cancelled. You can enter after the countdown." : "");
    }
    if (model) await releaseModel(model);
  }, [releaseModel]);

  useEffect(() => {
    mounted.current = true;
    const leave = () => { void disconnect(); };
    window.addEventListener("pagehide", leave);
    return () => { mounted.current = false; window.removeEventListener("pagehide", leave); void disconnect(); };
  }, [disconnect]);

  useEffect(() => {
    const update = () => {
      cooldownUntil.current = Math.max(cooldownUntil.current, readCooldown());
      setCooldownSeconds(Math.max(0, Math.ceil((cooldownUntil.current - Date.now()) / 1000)));
    };
    const shared = (event: StorageEvent) => { if (event.key === REACTOR_COOLDOWN_KEY) update(); };
    update();
    const timer = setInterval(update, 1000);
    window.addEventListener("storage", shared);
    return () => { clearInterval(timer); window.removeEventListener("storage", shared); };
  }, []);

  const dispatch = useCallback((model: LingbotWorld2Model, command: AxisCommand) => {
    switch (command.method) {
      case "setMoveLongitudinal": return model.setMoveLongitudinal(command.params);
      case "setMoveLateral": return model.setMoveLateral(command.params);
      case "setLookHorizontal": return model.setLookHorizontal(command.params);
      case "setLookVertical": return model.setLookVertical(command.params);
    }
  }, []);

  const wake = useCallback(() => {
    lastInput.current = Date.now();
    const model = client.current;
    if (pausedRef.current && model && ready.current) {
      pausedRef.current = false; setPaused(false);
      void model.resume().catch(report);
    }
  }, [report]);

  const sync = useCallback((next: Axes) => {
    axes.current = next;
    const model = client.current;
    if (!model || !ready.current) return;
    const movingBefore = sent.current.move_longitudinal !== "idle" || sent.current.move_lateral !== "idle";
    const movingAfter = next.move_longitudinal !== "idle" || next.move_lateral !== "idle";
    for (const command of diffAxes(sent.current, next)) void dispatch(model, command).catch(report);
    sent.current = next;
    if (movingBefore !== movingAfter && !sequence.current) {
      requestedPrompt.current = composeGymPrompt(roomRef.current, phaseRef.current, movingAfter, variationRef.current, customTaskRef.current, directionRef.current);
      void model.setPrompt({ prompt: requestedPrompt.current }).catch(report);
    }
  }, [dispatch, report]);

  const cancelSequence = useCallback((restorePrompt = true) => {
    if (!sequence.current) return;
    keys.current.clear(); sync(IDLE_AXES);
    sequence.current = null; setSequenceState(null); setDemoFinished(false);
    if (restorePrompt && client.current && ready.current) {
      requestedPrompt.current = composeGymPrompt(roomRef.current, phaseRef.current, false, variationRef.current, customTaskRef.current, directionRef.current);
      void client.current.setPrompt({ prompt: requestedPrompt.current }).catch(report);
    }
  }, [report, sync]);

  const sendSequenceStep = useCallback((run: GenerationSequence) => {
    const model = client.current, step = run.steps[run.index];
    if (!model || !ready.current || !step) return;
    sequenceUpdated.current = Date.now(); wake();
    if (step.phase) { phaseRef.current = step.phase; setPhase(step.phase); }
    sync({ ...IDLE_AXES, ...step.axes });
    setRenderedPhase("pending"); requestedPrompt.current = step.prompt;
    void model.setPrompt({ prompt: step.prompt }).then(reply => {
      if (!reply && client.current === model && sequence.current?.steps === run.steps)
        throw new Error(model.getLastError()?.message ?? "Reactor did not accept the next sequence step.");
    }).catch(cause => { if (sequence.current?.steps === run.steps) { cancelSequence(false); report(cause); } });
  }, [cancelSequence, report, sync, wake]);

  const startSequence = (run: GenerationSequence) => {
    if (!client.current || !ready.current) return;
    keys.current.clear(); customTaskRef.current = ""; setCustomTask("");
    setDemoFinished(false); sequence.current = run; setSequenceState(run); sendSequenceStep(run);
  };

  const sequenceChunk = (chunk: Parameters<typeof acceptSequenceChunk>[1]) => {
    const run = sequence.current;
    if (!run) return;
    const next = acceptSequenceChunk(run, chunk);
    if (next === run) return;
    sequenceUpdated.current = Date.now(); lastInput.current = Date.now();
    if (next.index === next.steps.length) {
      sync(IDLE_AXES); sequence.current = null; setSequenceState(null);
      if (next.mode === "task") setDemoFinished(true);
      if (next.destination) onDoor(next.destination);
    } else {
      sequence.current = next; setSequenceState(next);
      if (next.index !== run.index) sendSequenceStep(next);
    }
  };

  useEffect(() => {
    if (!sequenceState) return;
    const timer = setInterval(() => {
      if (sequence.current && Date.now() - sequenceUpdated.current > 45_000) {
        cancelSequence(); report(new Error("The sequence stopped because Reactor stopped returning matching frames. You can try again."));
      }
    }, 1000);
    return () => clearInterval(timer);
  }, [!!sequenceState, cancelSequence, report]);

  const seed = useCallback(async (model: LingbotWorld2Model) => {
    const revision = ++generation.current;
    const target = roomRef.current, targetImage = imageRef.current, targetVariation = variationRef.current;
    const current = () => mounted.current && client.current === model && generation.current === revision;
    const preceding = seedQueue.current;
    let release: () => void = () => {};
    seedQueue.current = new Promise<void>(resolve => { release = resolve; });
    ready.current = false; keys.current.clear(); axes.current = IDLE_AXES; sent.current = IDLE_AXES;
    sequence.current = null; setSequenceState(null); setDemoFinished(false);
    phaseRef.current = "ready"; setPhase("ready"); setFrames(0); setPlaying(false); setBusy(true); setPaused(false); pausedRef.current = false;
    customTaskRef.current = ""; setCustomTask(""); setTaskDraft("");
    setRenderedPhase("pending"); setRenderedAction("still");
    setMessage(`Generating ${target.theme.name}…`);
    try {
      await preceding;
      if (!current()) return;
      const response = await fetch(targetImage);
      if (!response.ok) throw new Error("The room's starting frame could not be loaded");
      const blob = await response.blob();
      if (!current()) return;
      const file = await model.uploadFile(blob, { name: `${target.theme.id}.jpg` });
      if (!current()) return;
      await model.reset();
      if (!current()) return;
      const accepted = await model.setImage({ image: file });
      if (!accepted) throw new Error(model.getLastError()?.message ?? "Reactor did not accept the starting image");
      if (!current()) return;
      requestedPrompt.current = composeGymPrompt(target, "ready", false, targetVariation, "", directionRef.current);
      const prompt = await model.setPrompt({ prompt: requestedPrompt.current });
      if (!prompt) throw new Error(model.getLastError()?.message ?? "Reactor did not accept the scene prompt");
      if (!current()) return;
      await model.setSeed({ seed: 1900 + target.index + targetVariation * 101 + target.depth * 17 });
      await model.setRotationSpeedDeg({ rotation_speed_deg: 2 });
      await model.setMoveLongitudinal({ move_longitudinal: "idle" });
      await model.setMoveLateral({ move_lateral: "idle" });
      await model.setLookHorizontal({ look_horizontal: "idle" });
      await model.setLookVertical({ look_vertical: "idle" });
      if (!current()) return;
      await model.start();
      if (current()) { ready.current = true; setMessage("Waiting for generated world frames…"); lastInput.current = Date.now(); }
    } catch (cause) {
      if (current()) { report(cause); await disconnect("Generation stopped. You can reconnect."); }
    } finally { release(); }
  }, [disconnect, report]);

  const connect = async () => {
    if (client.current || connection.current) return;
    cooldownUntil.current = Math.max(cooldownUntil.current, readCooldown());
    if (cooldownUntil.current > Date.now()) {
      setCooldownSeconds(Math.ceil((cooldownUntil.current - Date.now()) / 1000));
      return;
    }
    const run = new AbortController(); connection.current = run;
    lastInput.current = Date.now();
    const retryDeadline = Date.now() + 120_000;
    const requested = () => mounted.current && connection.current === run && !run.signal.aborted;
    setError(null); setRetryMessage(""); setStatus("connecting"); setBusy(true);
    setMessage("Preparing your Reactor connection…");
    try {
      await closing.current;
      for (let attempt = 0; attempt <= MAX_CONNECTION_RETRIES && requested(); attempt++) {
        // Both attempt budgets poll the same session; neither creates new sessions.
        // New session requests remain serialized by the app's connection guard.
        const model = new LingbotWorld2Model({
          maxSessionAttempts: 30, maxSdpAttempts: 20, readyTimeoutMs: 60_000,
          sdpBackoffInitialMs: 500, sdpBackoffMaxMs: 2000, sdpBackoffMultiplier: 1.5,
        }); client.current = model;
        let connected = false;
        const current = () => mounted.current && !run.signal.aborted && client.current === model;
        setStatus("connecting"); setBusy(true); setRetryPending(false); setMessage("Connecting to Reactor LingBot World 2…");
        model.on("statusChanged", value => {
          if (!current()) return;
          if (value !== "disconnected") {
            setStatus(value);
            if (value === "waiting") setMessage("Waiting for Reactor to prepare the live video connection…");
          }
          // connect() owns its failure until it rejects; disposing here loses the quota hint.
          else if (connected) void disconnect("Reactor disconnected. Reconnect to continue.");
        });
        model.on("error", value => { if (current() && connected) report(value); });
        model.onCommandError(value => { if (current()) report(new Error(`${value.command}: ${value.reason}`)); });
        model.onChunkComplete(value => {
          if (!current() || !ready.current || !value.active_prompt.startsWith(`Photorealistic ${roomRef.current.theme.name} `)) return;
          setFrames(count => count + value.frames_emitted); setBusy(false); setMessage("Reactor world live");
          setRenderedAction(value.active_action);
          if (value.active_prompt === requestedPrompt.current) setRenderedPhase(phaseRef.current);
          if (video.current && video.current.readyState >= 2) setPlaying(true);
          sequenceChunk(value);
        });
        model.onMainVideo((_track, stream) => {
          if (!current() || !video.current) return;
          video.current.srcObject = stream;
          void video.current.play().catch(() => { if (current()) report(new Error("Click the world view to start playback.")); });
        });
        try {
          const response = await fetch("/api/reactor/token?model=lingbot-world-2", { cache: "no-store", signal: run.signal });
          const token = await response.json();
          if (!response.ok) throw Object.assign(new Error(token.error ?? "Reactor authentication failed"), {
            status: response.status, code: token.code, quota_type: token.quota_type,
            retry_after_seconds: token.retry_after_seconds ?? Number(response.headers.get("Retry-After")),
          });
          if (!current()) return;
          // The same token authorizes this session's later recording download.
          const jwt = token.jwt as string;
          await model.connect(jwt);
          if (current()) { connected = true; tokenRef.current = jwt; setCooldownSeconds(0); setRetryMessage(""); }
          if (current()) await seed(model);
          return;
        } catch (cause) {
          if (!current()) return;
          client.current = null;
          await releaseModel(model);
          if (!requested()) return;
          const failure = connectionFailure(cause);
          if (!failure.retryable) { report(new Error(failure.message)); return; }
          const delay = Math.max(failure.retryAfterMs, 6000 * 2 ** attempt) + 500 + Math.random() * 500;
          cooldownUntil.current = saveCooldown(delay);
          setCooldownSeconds(Math.ceil((cooldownUntil.current - Date.now()) / 1000));
          setBusy(false); setStatus("cooldown");
          const retry = attempt < MAX_CONNECTION_RETRIES && cooldownUntil.current <= retryDeadline;
          setRetryPending(retry);
          setRetryMessage(retry ? `${failure.message} Retrying automatically (${attempt + 1}/${MAX_CONNECTION_RETRIES}).` : `${failure.message} Automatic retries have stopped. Try again after the countdown.`);
          if (!retry) return;
          do {
            if (cooldownUntil.current > retryDeadline) {
              setRetryMessage(`${failure.message} Automatic retries have stopped. Try again after the countdown.`);
              return;
            }
            await waitForRetry(Math.max(0, cooldownUntil.current - Date.now()), run.signal);
            cooldownUntil.current = Math.max(cooldownUntil.current, readCooldown());
          } while (requested() && cooldownUntil.current > Date.now());
        }
      }
    } catch (cause) { if (requested()) report(cause); }
    finally {
      if (connection.current === run) {
        connection.current = null;
        if (mounted.current && !client.current) { setStatus("disconnected"); setBusy(false); setRetryPending(false); }
      }
    }
  };

  useEffect(() => {
    variationRef.current = 0; setVariation(0); setError(null);
    directionRef.current = ""; setDirection(""); setDirectionDraft(""); setDirectorOpen(false);
    const model = client.current;
    if (model?.getStatus() === "ready") void seed(model);
  }, [room.path, image, seed]);

  useEffect(() => {
    if (!active) return;
    const timer = setInterval(() => {
      const quiet = Date.now() - lastInput.current;
      if (quiet > 120_000 && ready.current) void disconnect("Session released after two idle minutes. Enter again to continue.");
      else if (quiet > 45_000 && ready.current && !pausedRef.current) {
        pausedRef.current = true; setPaused(true);
        void client.current?.pause().catch(report);
      }
    }, 1000);
    return () => clearInterval(timer);
  }, [active, disconnect, report]);

  const perform = useCallback((next: TaskPhase) => {
    const model = client.current;
    if (!model || !ready.current) return;
    cancelSequence(false); setDemoFinished(false); wake(); phaseRef.current = next; setPhase(next);
    customTaskRef.current = ""; setCustomTask("");
    setRenderedPhase("pending");
    requestedPrompt.current = composeGymPrompt(roomRef.current, next, axes.current.move_longitudinal !== "idle" || axes.current.move_lateral !== "idle", variationRef.current, "", directionRef.current);
    void model.setPrompt({ prompt: requestedPrompt.current }).catch(report);
  }, [cancelSequence, report, wake]);

  const directTask = () => {
    const model = client.current, instruction = taskDraft.trim().replace(/\s+/g, " ").slice(0, 220);
    if (!model || !ready.current || !instruction) return;
    cancelSequence(false); setDemoFinished(false);
    wake(); customTaskRef.current = instruction; setCustomTask(instruction);
    phaseRef.current = "execute"; setPhase("execute"); setRenderedPhase("pending");
    requestedPrompt.current = composeGymPrompt(roomRef.current, "execute", axes.current.move_longitudinal !== "idle" || axes.current.move_lateral !== "idle", variationRef.current, instruction, directionRef.current);
    void model.setPrompt({ prompt: requestedPrompt.current }).then(reply => {
      if (!reply && client.current === model) report(new Error(model.getLastError()?.message ?? "Reactor did not accept this task. Try a shorter instruction."));
    }).catch(report);
  };

  const directScene = () => {
    const model = client.current;
    if (!model || !ready.current) return;
    cancelSequence(false); wake();
    const value = directionDraft.trim().replace(/\s+/g, " ").slice(0, 220);
    directionRef.current = value; setDirection(value); setRenderedPhase("pending");
    requestedPrompt.current = composeGymPrompt(roomRef.current, phaseRef.current, axes.current.move_longitudinal !== "idle" || axes.current.move_lateral !== "idle", variationRef.current, customTaskRef.current, value);
    void model.setPrompt({ prompt: requestedPrompt.current }).then(reply => {
      if (!reply && client.current === model) report(new Error(model.getLastError()?.message ?? "Reactor did not accept this scene direction."));
    }).catch(report);
  };

  useEffect(() => {
    const down = (event: KeyboardEvent) => {
      if (event.metaKey || event.ctrlKey || event.altKey || isTypingTarget(event.target as HTMLElement)) return;
      const key = event.key.toLowerCase();
      if (key === "e" && !event.repeat) { const phases: TaskPhase[] = ["ready", ...taskPhases(roomRef.current)]; event.preventDefault(); perform(phases[(phases.indexOf(phaseRef.current) + 1) % phases.length]); return; }
      if (!["w", "a", "s", "d", "r", "f", "arrowleft", "arrowright", "arrowup", "arrowdown"].includes(key)) return;
      if (!ready.current) return;
      event.preventDefault(); cancelSequence(); wake(); keys.current.add(key); sync(axesFromInput(keys.current));
    };
    const up = (event: KeyboardEvent) => { if (keys.current.delete(event.key.toLowerCase())) sync(axesFromInput(keys.current)); };
    const stop = () => { cancelSequence(); keys.current.clear(); sync(IDLE_AXES); };
    const hide = () => { if (document.hidden) { stop(); void disconnect("Session released when the tab was hidden."); } };
    window.addEventListener("keydown", down); window.addEventListener("keyup", up); window.addEventListener("blur", stop); document.addEventListener("visibilitychange", hide);
    return () => { stop(); window.removeEventListener("keydown", down); window.removeEventListener("keyup", up); window.removeEventListener("blur", stop); document.removeEventListener("visibilitychange", hide); };
  }, [perform, sync, wake, disconnect, cancelSequence]);

  const press = (key: string, held: boolean) => {
    if (held) { cancelSequence(); wake(); keys.current.add(key); } else keys.current.delete(key);
    sync(axesFromInput(keys.current));
  };
  const startDrag = (event: PointerEvent<HTMLDivElement>) => {
    if (!ready.current || event.button !== 0 || (event.target as HTMLElement).closest("button,a,input,textarea,select,label,[contenteditable]")) return;
    cancelSequence();
    event.currentTarget.setPointerCapture(event.pointerId); drag.current = { x: event.clientX, y: event.clientY }; wake();
  };
  const moveDrag = (event: PointerEvent<HTMLDivElement>) => {
    const previous = drag.current;
    if (!previous) return;
    clearTimeout(previous.timer);
    sync(axesFromInput(keys.current, { dx: event.clientX - previous.x, dy: event.clientY - previous.y }, 2));
    previous.x = event.clientX; previous.y = event.clientY; wake();
    previous.timer = setTimeout(() => sync(axesFromInput(keys.current)), 130);
  };
  const endDrag = () => { if (!drag.current) return; clearTimeout(drag.current.timer); drag.current = null; sync(axesFromInput(keys.current)); };

  const capture = async () => {
    const model = client.current;
    if (!model) return;
    wake(); setCaptureBusy(true);
    try {
      const clip = await model.requestClip(10);
      await downloadClipAsFile(clip, `${room.theme.id}-reactor-world.mp4`, { jwt: tokenRef.current ?? undefined });
    } catch (cause) { report(cause); }
    finally { if (mounted.current) setCaptureBusy(false); }
  };

  return <div className={styles.world} data-testid="reactor-gym" data-reactor-status={status} data-reactor-frames={frames} data-task-phase={phase} data-rendered-task-phase={renderedPhase} data-rendered-action={renderedAction} data-robot-instruction={customTask}
    data-director-mode={sequenceState?.mode ?? "idle"} data-sequence-step={sequenceState?.index ?? 0} data-sequence-complete={demoFinished} data-scene-direction={direction}
    tabIndex={0} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}>
    {!live && <video key={generated?.video ?? room.video} className={styles.backdrop} src={generated?.video ?? room.video} poster={image} autoPlay muted loop playsInline aria-label="Recorded Reactor world preview" />}
    <video ref={video} className={`${styles.backdrop} ${live ? styles.visible : styles.hidden}`} autoPlay muted playsInline
      onPlaying={() => setPlaying(true)} onClick={() => void video.current?.play()} aria-label="Live Reactor generated world" />
    <div className={styles.shade} />
    <div className={styles.heading}><small>EXPERIMENT 03 <span>REACTOR WORLD MODEL</span></small><h1>{room.theme.name}</h1><p>{room.theme.description}</p></div>
    <div className={styles.status}><i className={live ? styles.live : ""} />{live ? paused ? "Paused · move to resume" : "LIVE / LINGBOT WORLD 2" : cooldownSeconds ? "REACTOR COOLDOWN" : active ? "CONNECTING TO REACTOR" : generated?.model === "reactor/lingbot-world-2" ? "RECORDED LINGBOT WORLD" : "RECORDED REACTOR PREVIEW"}
      <span>{live ? `${frames} generated frames` : cooldownSeconds ? `Available in ${cooldownSeconds} s` : "Enter to control the world"}</span></div>
    {!active && <div className={styles.entry}><span className={styles.orb}>R</span><h2>Step inside the world.</h2><p className={retryMessage ? styles.retryNotice : undefined} role={retryMessage ? "status" : undefined}>{retryMessage || "The room, robot and objects are generated together as you move."}</p>
      <button disabled={!configured || cooldownSeconds > 0 || retryPending} onClick={() => void connect()}>{cooldownSeconds ? `${retryPending ? "Retrying" : "Available"} in ${cooldownSeconds} s` : "Enter Reactor world"} <span>↗</span></button>
      {retryPending && <button className={styles.cancelRetry} onClick={() => void disconnect("Automatic retry cancelled.")}>Cancel automatic retry</button>}
      <small>{configured ? "Live generation starts when you enter." : "Set REACTOR_API_KEY to enable live worlds."}</small></div>}
    {active && busy && <div className={styles.generating} role="status"><i />{message}<button onClick={() => void disconnect()}>Cancel</button></div>}
    {live && <div className={styles.sceneDirector}><button aria-expanded={directorOpen} onClick={() => setDirectorOpen(value => !value)}>Direct the world <span>{directorOpen ? "−" : "+"}</span></button>
      {directorOpen && <form onSubmit={event => { event.preventDefault(); directScene(); }}><label htmlFor="reactor-scene-direction">Change the atmosphere, materials or surroundings</label>
        <textarea id="reactor-scene-direction" aria-label="Describe the world" value={directionDraft} maxLength={220} onChange={event => setDirectionDraft(event.target.value)} placeholder="Soft evening light, brushed steel benches, rain on the windows…" />
        <div className={styles.scenePresets}>{[["Golden hour", "Warm late-afternoon sunlight, soft long shadows and subtle dust in the light."], ["Steel & glass", "Brushed stainless-steel work surfaces, clear glass partitions and soft reflected light."], ["Rain outside", "Rain on the windows, an overcast sky and warm indoor task lighting."]].map(([label, value]) => <button key={label} type="button" onClick={() => setDirectionDraft(value)}>{label}</button>)}</div>
        <button type="submit" disabled={busy}>Apply to Reactor ↗</button><small>{direction ? renderedPhase === "pending" ? "Waiting for Reactor to use this direction…" : "Reactor is generating with your scene direction." : "Change the live world without starting a new session."}</small>
      </form>}
    </div>}
    {live && nextRoom && <button className={styles.portal} disabled={!!sequenceState || busy} aria-label={`Walk to ${nextRoom.theme.name}`} onClick={() => startSequence(doorSequence(room, nextRoom, directionRef.current))}><small>NEXT ROOM</small><strong>{nextRoom.theme.name}</strong><span>Generate a walk to this room ↗</span></button>}
    <div className={styles.bottom}>
      <div className={styles.task}><div className={styles.taskTitle}><div><small>ONE ROOM · ONE ROBOT TASK</small><h2>{room.goal}</h2></div><span>{room.kind.toUpperCase()}</span><button className={styles.runTask} aria-label="Run task with Reactor" disabled={!live || busy || !!sequenceState} onClick={() => startSequence(taskSequence(room, variationRef.current, directionRef.current))}>▷ Run task</button></div>
        <div className={styles.phases}>{taskPhases(room).map((item, index) => <button key={item} aria-pressed={!customTask && phase === item} disabled={!live || busy} onClick={() => perform(item)}><b>{index + 1}</b>{phaseLabel(room, item)}</button>)}</div>
        {sequenceState && <div className={styles.sequenceProgress} role="status"><span>{sequenceState.index + 1} / {sequenceState.steps.length} · {sequenceState.steps[sequenceState.index].label}</span><progress aria-label="Reactor sequence progress" max={sequenceState.steps.length} value={sequenceState.index + sequenceState.received / sequenceState.steps[sequenceState.index].frames} /><button onClick={() => cancelSequence()}>Stop sequence</button></div>}
        {live && <form className={styles.directTask} onSubmit={event => { event.preventDefault(); directTask(); }}><label htmlFor="reactor-robot-task">Direct the robot</label><input id="reactor-robot-task" aria-label="Describe a robot task" value={taskDraft} maxLength={220} disabled={busy} onChange={event => setTaskDraft(event.target.value)} placeholder={`Place the ${room.theme.object} gently in the tray…`} /><button type="submit" disabled={busy || !taskDraft.trim()}>Generate task ↗</button></form>}
        <p>{live ? demoFinished ? "Task sequence generated · Run it again or take control." : customTask || `${phaseLabel(room, phase)} · Press E for the next task instruction.` : "Enter the live world to try the robot task."}<span>Visual robot experiment · contacts are unverified</span></p>
      </div>
      <div className={styles.toolbar}><div className={styles.hint}><kbd>W A S D</kbd> walk <span>·</span> drag / arrows look <span>·</span> <kbd>E</kbd> robot task</div><div className={styles.actions}>
        {active && <><button disabled={busy || !live} onClick={() => { variationRef.current++; setVariation(variationRef.current); const model = client.current; if (model) void seed(model); }}>New variation{variation ? ` ${variation}` : ""}</button>
          <button disabled={!live || captureBusy} onClick={() => void capture()}>{captureBusy ? "Saving…" : "Save 10 s clip"}</button><button onClick={() => void disconnect()}>Leave Reactor</button></>}
        <button onClick={() => { void disconnect(); onPhysics(); }}>Physics prototype ↗</button>
      </div></div>
      {live && <div className={styles.touch} aria-label="World movement controls">{[["arrowleft", "↶"], ["w", "↑"], ["arrowright", "↷"], ["a", "←"], ["s", "↓"], ["d", "→"]].map(([key, label]) => <button key={key} aria-label={`Walk ${key}`} onPointerDown={event => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); press(key, true); }} onPointerUp={() => press(key, false)} onPointerCancel={() => press(key, false)} onLostPointerCapture={() => press(key, false)}>{label}</button>)}</div>}
    </div>
    {error && <div className={styles.error} role="alert">{error}<button aria-label="Dismiss Reactor error" onClick={() => setError(null)}>×</button></div>}
  </div>;
}
